### ISSUE TITLE
 Failed validating 'multipleOf' in schema['properties']['SCOREPERCENT']

### ISSUE THREAD

**Issue by visch** [singer-io/target-csv#31]
jsonschema.exceptions.ValidationError: 66.666667 is not a multiple of 1e-06

target-csv | Traceback (most recent call last):
target-csv | File "/home/visch/git/oracle2mssql/oracle2mssql/.meltano/loaders/target-csv/venv/bin/target-csv", line 8, in
target-csv | sys.exit(main())
target-csv | File "/home/visch/git/oracle2mssql/oracle2mssql/.meltano/loaders/target-csv/venv/lib/python3.8/site-packages/target_csv.py", line 141, in main
target-csv | state = persist_messages(config.get('delimiter', ','),
target-csv | File "/home/visch/git/oracle2mssql/oracle2mssql/.meltano/loaders/target-csv/venv/lib/python3.8/site-packages/target_csv.py", line 59, in persist_messages
target-csv | validators[o['stream']].validate(o['record'])
target-csv | File "/home/visch/git/oracle2mssql/oracle2mssql/.meltano/loaders/target-csv/venv/lib/python3.8/site-packages/jsonschema/validators.py", line 130, in validate
target-csv | raise error
target-csv | jsonschema.exceptions.ValidationError: 66.666667 is not a multiple of 1e-06
target-csv |
target-csv | Failed validating 'multipleOf' in schema['properties']['SCOREPERCENT']:
target-csv | {'exclusiveMaximum': True,
target-csv | 'exclusiveMinimum': True,
target-csv | 'maximum': 1000000000000,
target-csv | 'minimum': -1000000000000,
target-csv | 'multipleOf': 1e-06,
target-csv | 'type': ['null', 'number']}
target-csv |
target-csv | On instance['SCOREPERCENT']:
target-csv | 66.666667

**Comment by visch** [comment]
This has been fixed in target-postgres

https://github.com/datamill-co/target-postgres/pull/179/files
